export const state = {
  appId: null,
  currentUser: null,
  currentUserProfile: null,
  userMovieList: new Map(),
  myListPageMovies: [],
  currentPage: 'home',
  currentModalMovie: null,
  currentModalCredits: null,
  firestoreUnsubscribe: null,
  followingUnsubscribe: null,
  activeMovieFilters: [],
  activeSeriesFilters: [],
  availableMoviesForRecommendation: [],
  homeRuntimeBackfillInProgress: false,
  userFollowing: new Map(),
  followingProjectsCache: new Map(),
  userFollows: new Map(),
  userFollowsUnsubscribe: null,
  suggestedUsers: [],
  suggestedUsersUnsubscribe: null,
  activityEvents: [],
  activityUnsubscribe: null,
  activityRemoteAvailable: true,
  profileMetadataBackfillInProgress: false,
  forumPosts: [],
  forumUnsubscribe: null,
  forumCommentUnsubscribes: new Map(),
  forumCommentsByPost: new Map()
};
